//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWalker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Walker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Walker()
        {
            this.Walks = new HashSet<Walk>();
        }
    
        public string FName { get; set; }
        public string LName { get; set; }
        public string Address { get; set; }
        public string DateOfBirth { get; set; }
        public string Phone { get; set; }
        public int WalkerID { get; set; }
        public string Rating { get; set; }
        public string Experience { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Walk> Walks { get; set; }
    }
}
