//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWalker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Walk
    {
        public int WalkID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> PetID { get; set; }
        public Nullable<int> WalkerID { get; set; }
        public string Rate { get; set; }
        public string Length { get; set; }
        public string Price { get; set; }
        public string Date { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Pet Pet { get; set; }
        public virtual Walker Walker { get; set; }
    }
}
